name: Docker

on:
  workflow_dispatch:

jobs:
  publish-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Hub login
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          echo "${DOCKERHUB_PASSWORD}" | docker login \
            --username "${DOCKERHUB_USERNAME}" \
            --password-stdin
      - name: Run buildx and push
        env:
          DOCKERHUB_REPO: komoridev/koishi-litex
          GITHUB_REPO: ${{ github.repository }}
        run: |
          TAG=$(curl "https://api.github.com/repos/${GITHUB_REPO}/releases/latest" | jq -r '.tag_name')
          NAME=$(cat package.json | jq -r '.name' | sed -E 's/.+\///')
          LINK="https://github.com/${GITHUB_REPO}/releases/download/$TAG/$NAME-$TAG-linux-"
          docker buildx build \
            --build-arg LINK=$LINK \
            --output "type=image,push=true" \
            --platform linux/amd64,linux/arm64 \
            --tag ${DOCKERHUB_REPO}:$TAG \
            --tag ${DOCKERHUB_REPO}:latest \
            --file Dockerfile \
            .
      - name: Docker Hub logout
        if: always()
        run: docker logout
